# Generated by Django 2.2.4 on 2020-01-17 15:48

from django.db import migrations
import phonenumbers


def normalization_phone(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        parsed_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(parsed_number):
            flat.owner_phone_pure = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
            flat.save()


def remove_normalized_phone(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        flat.owner_phone_pure = ""
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(normalization_phone, remove_normalized_phone)
    ]
