# Generated by Django 2.2.4 on 2020-01-30 15:37

from django.db import migrations


def move_owners_to_owner_model(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_phone_pure=flat.owner_phone_pure)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(move_owners_to_owner_model)
    ]
