# Generated by Django 2.2.4 on 2020-02-03 14:50

from django.db import migrations


def move_owners_to_owner_model(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    for owner in Owner.objects.all():
        print(owner)
        flats = Flat.objects.filter(owner=owner.owner, owners_phonenumber=owner.owners_phonenumber)
        for flat in flats:
            print(flat)
            owner.owners_flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200203_1708'),
    ]

    operations = [
        migrations.RunPython(move_owners_to_owner_model)
    ]
